config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :signs
    resources :users
    resources :user_sign_transfers, only: %i[new create]
    resources :approved_user_applications, only: %i[index show] do
      member do
        post :accept
        post :decline
      end
    end
    resources :topics
    resources :comment_reports
    resources :exports, only: :index do
      get :published_signs, on: :collection
      get :users, on: :collection
      get :signbank, on: :collection
    end
    root to: "signs#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resource :styleguide, only: :show
  resources :users, only: :show, param: :username,
                    constraints: {
                      # Route constraints must be unanchored
                      username: Regexp.new(User::USERNAME_REGEXP.source.gsub(/\\A|\\Z/, ""))
                    }

  require "sidekiq/web"
  authenticate :user, ->(u) { u.administrator? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  root "home#index"
  resources :search, only: [:index]
  resources :public_signs, only: [:index]
  resources :approved_user_applications, only: %i[new create]
  resources :signs, except: %i[index] do
    resources :share, only: %i[show create destroy], controller: :sign_share, param: :token
    resources :comments, only: %i[create edit update destroy], controller: :sign_comments do
      resources :reports, only: :create, controller: :comment_reports
      resource :video, only: %i[update destroy], controller: :sign_video_comment
    end
    resources :video_comment, only: %i[create], controller: :sign_video_comment
    resources :sign_attachments, only: %i[create update destroy],
                                 path: "/:attachment_type",
                                 as: :attachments,
                                 constraints: { attachment_type: /usage_examples|illustrations/ }
    resource :agreement, only: %i[create destroy], controller: :sign_agreement
    resource :disagreement, only: %i[create destroy], controller: :sign_disagreement
    Sign.aasm.events.map(&:name).each do |event_name|
      patch event_name, on: :member, controller: :sign_workflow
    end

    collection do
      resources :batch_operation, only: :create,
                                  as: :signs_batch_operations,
                                  controller: :sign_batch_operations
    end
  end
  resources :sign_requests, only: :index

  resources :topics, only: %i[index show] do
    get :uncategorised, on: :collection
  end

  resources :folders do
    resources :share, only: %i[show create destroy], controller: :folder_share, param: :token
    resources :collaborations, controller: :collaborations
  end

  get "/videos/:id/:preset" => "videos#show", as: :video

  resources :folder_memberships, only: %i[create destroy]

  scope "/user" do
    resources :signs, only: [:index], as: :user_signs
  end
  post "/rails/active_storage/direct_uploads" => "direct_uploads#create"

  ##
  # Workaround a "bug" in lighthouse CLI
  #
  # Lighthouse CLI (versions 5.4 - 5.6 tested) issues a `GET /asset-manifest.json`
  # request during its run - the URL seems to be hard-coded. This file does not
  # exist so, during tests, your test will fail because rails will die with a 404.
  #
  # Lighthouse run from Chrome Dev-tools does not have the same behaviour.
  #
  # This hack works around this. This behaviour might be fixed by the time you
  # read this. You can check by commenting out this block and running the
  # accessibility and performance tests. You are encouraged to remove this hack
  # as soon as it is no longer needed.
  #
  if defined?(Shakapacker) && Rails.env.test?
    # manifest paths depend on your shakapacker config so we inspect it
    manifest_path = Shakapacker::Configuration
                    .new(root_path: Rails.root, config_path: Rails.root.join("config/shakapacker.yml"), env: Rails.env)
                    .public_manifest_path
                    .relative_path_from(Rails.public_path)
                    .to_s
    get "/asset-manifest.json", to: redirect(manifest_path)
  end

  get "/sitemap.xml" => "sitemaps#index", defaults: { format: "xml" }, as: :sitemap

  # This route acts as a catch-all, and so should always be placed at the end of the routes declaration
  # block
  get "/:page" => "static#show", as: :page
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  scope :featured, -> { where.not(featured_at: nil).order(featured_at: :desc) }
  has_many :sign_topics, dependent: :destroy
  has_many :signs, through: :sign_topics

  NO_TOPIC_DESCRIPTION = "Other signs".freeze

  def featured
    featured_at.present?
  end

  def featured=(value)
    self.featured_at = value.to_i == 1 ? Time.zone.now : nil
  end
end

app/controllers/admin/topics_controller.rb
module Admin
  class TopicsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = policy_scope(Topic)
              .order(name: :asc)
  end

  def show
    @topic = policy_scope(Topic).find(params[:id])

    search_results = TopicSignService.new(search:, relation: policy_scope(Sign), topic: @topic).process
    @signs = search_results.data
    @page = search_results.support

    authorize @topic
  end

  def uncategorised
    # "uncategorised" isn't a topic
    # it references signs that LACK a topic
    @topic = Topic.new(name: Topic::NO_TOPIC_DESCRIPTION)
    search_results ||= TopicSignService.new(search:, relation: policy_scope(Sign), topic: @topic).process
    @signs = search_results.data
    @page = search_results.support

    authorize @topic, :show?

    render :show
  end

  private

  def search
    @search ||= Search.new(params.permit(:page, :sort))
  end
end

app/views/topics/index.html.erb
<% provide(:title, "Topics") %>

<div class="grid-x">
  <nav class="cell shrink" aria-label="You are here:" role="navigation">
    <ul class="breadcrumbs">
      <li><a href="/">Home</a></li>
      <li>
        <span class="show-for-sr">Current: </span> Topics
      </li>
    </ul>
  </nav>

  <div class="grid-x cell list">
    <div class="list__title list__section cell">
      <h1>Topics</h1>
      <%= link_to(public_signs_path, class: "button royal primary") do %>
        See all signs
      <% end %>
    </div>
    <hr class="list__divider">
    <div class="list__section list__section--topics cell">
      <% @topics.each do |topic| %>
        <%= link_to content_tag(:p, topic.name, class: "royal"), topic, class: "no-underline" %>
      <% end %>
    </div>
    <div class="list__section list__section--topics cell">
      <%= link_to Topic::NO_TOPIC_DESCRIPTION, uncategorised_topics_path, class: "royal no-underline" %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<% provide(:title, @topic.name) %>

<div class="grid-x margin-vertical-2">
  <div class="cell auto">
    <h2 class="normal">
      <%= [@page[:limit], @page[:total]].min %> of <%= @page[:total] %> signs
    </h2>
  </div>

  <div class="cell shrink">
    <%= render "search/sort_by", page: @page unless @page[:total].zero? %>
  </div>
</div>
<hr class="list__divider list__divider--dark">

<div class="grid-x grid-margin-x">
  <nav class="cell shrink" aria-label="You are here:" role="navigation">
    <ul class="breadcrumbs">
      <li><a href="/">Home</a></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li>
        <span class="show-for-sr">Current: </span> <%= @topic.name %>
      </li>
    </ul>
  </nav>

  <div class="grid-x cell">
    <h1><%= @topic.name %></h1>
    <div class="sign-grid cell">
      <% @signs.for_cards.each do |sign| %>
        <%= render "signs/card", sign: sign %>
      <% end %>
    </div>
  </div>
</div>

<% if @page[:total] >= @page[:limit] %>
  <div class="cell auto text-center margin-2">
    <%= link_to "Show More", params.to_unsafe_h.merge(page: @page[:next_page], anchor: dom_id(@signs.last, :card)), class: "button primary" %>
  </div>
<% end %>