config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :signs
    resources :users
    resources :user_sign_transfers, only: %i[new create]
    resources :approved_user_applications, only: %i[index show] do
      member do
        post :accept
        post :decline
      end
    end
    resources :topics
    resources :comment_reports
    resources :exports, only: :index do
      get :published_signs, on: :collection
      get :users, on: :collection
      get :signbank, on: :collection
    end
    root to: "signs#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resource :styleguide, only: :show
  resources :users, only: :show, param: :username,
                    constraints: {
                      # Route constraints must be unanchored
                      username: Regexp.new(User::USERNAME_REGEXP.source.gsub(/\\A|\\Z/, ""))
                    }

  require "sidekiq/web"
  authenticate :user, ->(u) { u.administrator? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  root "home#index"
  resources :search, only: [:index]
  resources :public_signs, only: [:index]
  resources :approved_user_applications, only: %i[new create]
  resources :signs, except: %i[index] do
    resources :share, only: %i[show create destroy], controller: :sign_share, param: :token
    resources :comments, only: %i[create edit update destroy], controller: :sign_comments do
      resources :reports, only: :create, controller: :comment_reports
      resource :video, only: %i[update destroy], controller: :sign_video_comment
    end
    resources :video_comment, only: %i[create], controller: :sign_video_comment
    resources :sign_attachments, only: %i[create update destroy],
                                 path: "/:attachment_type",
                                 as: :attachments,
                                 constraints: { attachment_type: /usage_examples|illustrations/ }
    resource :agreement, only: %i[create destroy], controller: :sign_agreement
    resource :disagreement, only: %i[create destroy], controller: :sign_disagreement
    Sign.aasm.events.map(&:name).each do |event_name|
      patch event_name, on: :member, controller: :sign_workflow
    end

    collection do
      resources :batch_operation, only: :create,
                                  as: :signs_batch_operations,
                                  controller: :sign_batch_operations
    end
  end
  resources :sign_requests, only: :index

  resources :topics, only: %i[index show] do
    get :uncategorised, on: :collection
  end

  resources :folders do
    resources :share, only: %i[show create destroy], controller: :folder_share, param: :token
    resources :collaborations, controller: :collaborations
  end

  get "/videos/:id/:preset" => "videos#show", as: :video

  resources :folder_memberships, only: %i[create destroy]

  scope "/user" do
    resources :signs, only: [:index], as: :user_signs
  end
  post "/rails/active_storage/direct_uploads" => "direct_uploads#create"

  ##
  # Workaround a "bug" in lighthouse CLI
  #
  # Lighthouse CLI (versions 5.4 - 5.6 tested) issues a `GET /asset-manifest.json`
  # request during its run - the URL seems to be hard-coded. This file does not
  # exist so, during tests, your test will fail because rails will die with a 404.
  #
  # Lighthouse run from Chrome Dev-tools does not have the same behaviour.
  #
  # This hack works around this. This behaviour might be fixed by the time you
  # read this. You can check by commenting out this block and running the
  # accessibility and performance tests. You are encouraged to remove this hack
  # as soon as it is no longer needed.
  #
  if defined?(Shakapacker) && Rails.env.test?
    # manifest paths depend on your shakapacker config so we inspect it
    manifest_path = Shakapacker::Configuration
                    .new(root_path: Rails.root, config_path: Rails.root.join("config/shakapacker.yml"), env: Rails.env)
                    .public_manifest_path
                    .relative_path_from(Rails.public_path)
                    .to_s
    get "/asset-manifest.json", to: redirect(manifest_path)
  end

  get "/sitemap.xml" => "sitemaps#index", defaults: { format: "xml" }, as: :sitemap

  # This route acts as a catch-all, and so should always be placed at the end of the routes declaration
  # block
  get "/:page" => "static#show", as: :page
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  scope :featured, -> { where.not(featured_at: nil).order(featured_at: :desc) }
  has_many :sign_topics, dependent: :destroy
  has_many :signs, through: :sign_topics

  NO_TOPIC_DESCRIPTION = "Other signs".freeze

  def featured
    featured_at.present?
  end

  def featured=(value)
    self.featured_at = value.to_i == 1 ? Time.zone.now : nil
  end
end

app/controllers/admin/topics_controller.rb
module Admin
  class TopicsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = policy_scope(Topic)
              .order(name: :asc)
  end

  def show
    @topic = policy_scope(Topic).find(params[:id])

    search_results = TopicSignService.new(search:, relation: policy_scope(Sign), topic: @topic).process
    @signs = search_results.data
    @page = search_results.support

    authorize @topic
  end

  def uncategorised
    # "uncategorised" isn't a topic
    # it references signs that LACK a topic
    @topic = Topic.new(name: Topic::NO_TOPIC_DESCRIPTION)
    search_results ||= TopicSignService.new(search:, relation: policy_scope(Sign), topic: @topic).process
    @signs = search_results.data
    @page = search_results.support

    authorize @topic, :show?

    render :show
  end

  private

  def search
    @search ||= Search.new(params.permit(:page, :sort))
  end
end

app/views/admin/topics/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if accessible_action?(resource, :show) -%>
              <% if (attribute.name == "name") %>
                <%= link_to topic_path(resource) do %>
                  <%= render_field attribute %>
                <% end %>
              <% else %>
                 <%= render_field attribute %>
              <% end %>
            <% end -%>
          </td>
        <% end %>

        <td class="admin-icons">
          <button title="Options" class="button clear" data-toggle="<%= dom_id(resource, :options) %>">
            <%= inline_svg_pack_tag "static/images/options.svg", class: "icon--medium list__item__icon" %>
          </button>
        </td>
      </tr>
      <div class="list__item-menu__dropdown-pane list__item-menu__dropdown-pane--admin" id="<%= dom_id(resource, :options) %>" data-position="bottom" data-alignment="right" data-dropdown data-hover="true" data-hover-pane="true">
        <ul class="list__item-menu vertical icons">
          <li class="list__item-menu__menu-item">
            <%= link_to([:edit, namespace, resource]) do %>
              <%= inline_svg_pack_tag "static/images/edit.svg", class: "icon--medium" %>
             <span>Edit</span>
            <% end %>
          </li>
          <li class="list__item-menu__menu-item">
            <form class="button_to" method="post" action="<%= admin_topic_path(resource) %>">
              <input type="hidden" name="_method" value="delete" autocomplete="off" />

              <button data-turbo-confirm="<%= t("administrate.actions.confirm")%>" type="submit" class="button bold clear black drop-down""><%= inline_svg_pack_tag "static/images/trash.svg", class: "icon" %>Delete</button>
            </form>
          </li>
        </ul>
      </div>
    <% end %>
  </tbody>
</table>

app/views/admin/topics/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource]) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |_, attributes| -%>
    <% attributes.each do |attribute| %>
      <div class="form__section">
        <%= render_field attribute, f: f %>
      </div>
    <% end %>
  <% end -%>

  <hr class="form__divider">

  <div class="form__footer">
    <%= link_to t("administrate.actions.back"), :back, class: "button clear margin-right-1" %>
    <%= f.submit class: "button royal primary" %>
  </div>
<% end %>

app/views/admin/topics/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.show_resource", name: page.page_title),
      [namespace, page.resource],
      class: "button",
    ) if valid_action?(:show) && show_action?(:show, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/topics/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>
<div class="grid-x list list--admin">
  <% content_for(:title) do %>
    <%= display_resource_name(page.resource_name) %>
  <% end %>

  <div class="list__title list__title--admin cell grid-x align-middle">
    <h1 class="cell auto" id="page-title">
      <%= content_for(:title) %>
    </h1>
    <% if show_search_bar %>
      <div class="cell shrink margin-right-1">
        <%= render(
          "search",
          search_term: search_term,
          resource_name: display_resource_name(page.resource_name)
        ) %>
      </div>
    <% end %>
    <div class="cell shrink">
      <%= link_to(new_admin_topic_path(new_resource), class: "button royal primary") do %>
        <%= inline_svg_pack_tag "static/images/add-2.svg", class: "icon icon--white" %><span>New Topic</span>
      <% end %>
    </div>
  </div>

  <hr class="list__divider"/>

  <section class="cell">
    <%= render(
      "collection",
      collection_presenter: page,
      collection_field_name: resource_name,
      page: page,
      resources: resources,
      table_title: "page-title"
    ) %>

    <%= paginate resources, param_name: '_page' %>
  </section>
</div>

app/views/admin/topics/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<div class="grid-x margin-top-2">
  <div class="cell medium-8 form">
    <legend class="form__header">
      <h1 class="black">
        New Topic
      </h1>
    </legend>

    <hr class="form__divider">

    <%= render "form", page: page %>
  </div>
</div>