config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :signs
    resources :users
    resources :user_sign_transfers, only: %i[new create]
    resources :approved_user_applications, only: %i[index show] do
      member do
        post :accept
        post :decline
      end
    end
    resources :topics
    resources :comment_reports
    resources :exports, only: :index do
      get :published_signs, on: :collection
      get :users, on: :collection
      get :signbank, on: :collection
    end
    root to: "signs#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resource :styleguide, only: :show
  resources :users, only: :show, param: :username,
                    constraints: {
                      # Route constraints must be unanchored
                      username: Regexp.new(User::USERNAME_REGEXP.source.gsub(/\\A|\\Z/, ""))
                    }

  require "sidekiq/web"
  authenticate :user, ->(u) { u.administrator? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  root "home#index"
  resources :search, only: [:index]
  resources :public_signs, only: [:index]
  resources :approved_user_applications, only: %i[new create]
  resources :signs, except: %i[index] do
    resources :share, only: %i[show create destroy], controller: :sign_share, param: :token
    resources :comments, only: %i[create edit update destroy], controller: :sign_comments do
      resources :reports, only: :create, controller: :comment_reports
      resource :video, only: %i[update destroy], controller: :sign_video_comment
    end
    resources :video_comment, only: %i[create], controller: :sign_video_comment
    resources :sign_attachments, only: %i[create update destroy],
                                 path: "/:attachment_type",
                                 as: :attachments,
                                 constraints: { attachment_type: /usage_examples|illustrations/ }
    resource :agreement, only: %i[create destroy], controller: :sign_agreement
    resource :disagreement, only: %i[create destroy], controller: :sign_disagreement
    Sign.aasm.events.map(&:name).each do |event_name|
      patch event_name, on: :member, controller: :sign_workflow
    end

    collection do
      resources :batch_operation, only: :create,
                                  as: :signs_batch_operations,
                                  controller: :sign_batch_operations
    end
  end
  resources :sign_requests, only: :index

  resources :topics, only: %i[index show] do
    get :uncategorised, on: :collection
  end

  resources :folders do
    resources :share, only: %i[show create destroy], controller: :folder_share, param: :token
    resources :collaborations, controller: :collaborations
  end

  get "/videos/:id/:preset" => "videos#show", as: :video

  resources :folder_memberships, only: %i[create destroy]

  scope "/user" do
    resources :signs, only: [:index], as: :user_signs
  end
  post "/rails/active_storage/direct_uploads" => "direct_uploads#create"

  ##
  # Workaround a "bug" in lighthouse CLI
  #
  # Lighthouse CLI (versions 5.4 - 5.6 tested) issues a `GET /asset-manifest.json`
  # request during its run - the URL seems to be hard-coded. This file does not
  # exist so, during tests, your test will fail because rails will die with a 404.
  #
  # Lighthouse run from Chrome Dev-tools does not have the same behaviour.
  #
  # This hack works around this. This behaviour might be fixed by the time you
  # read this. You can check by commenting out this block and running the
  # accessibility and performance tests. You are encouraged to remove this hack
  # as soon as it is no longer needed.
  #
  if defined?(Shakapacker) && Rails.env.test?
    # manifest paths depend on your shakapacker config so we inspect it
    manifest_path = Shakapacker::Configuration
                    .new(root_path: Rails.root, config_path: Rails.root.join("config/shakapacker.yml"), env: Rails.env)
                    .public_manifest_path
                    .relative_path_from(Rails.public_path)
                    .to_s
    get "/asset-manifest.json", to: redirect(manifest_path)
  end

  get "/sitemap.xml" => "sitemaps#index", defaults: { format: "xml" }, as: :sitemap

  # This route acts as a catch-all, and so should always be placed at the end of the routes declaration
  # block
  get "/:page" => "static#show", as: :page
end

app/controllers/home_controller.rb
# Renders the home page.
class HomeController < ApplicationController
  layout -> { user_signed_in? ? "authenticated_home" : "home" }

  def index
    @recent_signs = policy_scope(Sign).recent.preview
    @viewed_signs = policy_scope(Sign).last(4)
  end
end

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<div class="grid-x home-main">
  <div class="home-main__container cell small-6 medium-3">
    <div class="home-main__icon">
      <%= inline_svg_pack_tag "static/images/home/folder.svg", aria_hidden: true %>
      <%= inline_svg_pack_tag "static/images/home/rectangle.svg", aria_hidden: true, class: "home-main__icon-shadow" %>
    </div>
    <h6>Upload and save favourites</h6>
    <p>Upload your recorded signs, keep them in your private folder and share links with others. </p>
    <%= link_to "Join NZSL Share", new_user_registration_path %>
  </div>

  <div class="home-main__container cell small-6 medium-3">
    <div class="home-main__icon">
      <%= inline_svg_pack_tag "static/images/home/conversation-check.svg", aria_hidden: true %>
      <%= inline_svg_pack_tag "static/images/home/rectangle.svg", aria_hidden: true, class: "home-main__icon-shadow" %>
    </div>
    <h6>Discuss signs</h6>
    <p>Approved members comment on signs, agree or disagree</p>
    <%= link_to "Learn more", edit_user_registration_path(anchor: "approved-member-information") %>
  </div>

  <div class="home-main__container cell small-6 medium-3">
    <div class="home-main__icon">
      <%= inline_svg_pack_tag "static/images/home/upload.svg", aria_hidden: true %>
      <%= inline_svg_pack_tag "static/images/home/rectangle.svg", aria_hidden: true, class: "home-main__icon-shadow" %>
    </div>
    <h6>Post public signs</h6>
    <p>Approved member can add new signs for everyone to see</p>
  </div>

  <div class="home-main__container cell small-6 medium-3">
    <div class="home-main__icon">
      <%= inline_svg_pack_tag "static/images/home/camera-2.svg", aria_hidden: true %>
      <%= inline_svg_pack_tag "static/images/home/rectangle.svg", aria_hidden: true, class: "home-main__icon-shadow" %>
    </div>
    <h6>Request signs</h6>
    <p>Request a sign from the community or ask questions about an existing sign.</p>
    <%= link_to "Request signs", sign_requests_path %>
  </div>

  <div id="recently-published" class="cell margin-top-1 home-main__signs">
    <div class="grid-x">
      <div class="cell auto">
        <h2>Recently Added</h2>
      </div>
      <div class="cell shrink">
        <%= link_to "See all", public_signs_path, class: "button primary" %>
      </div>
    </div>
    <div class="sign-grid sign-grid--not-bottom">
      <%= render partial: "signs/card", collection: @recent_signs, as: :sign %>
    </div>
  </div>

  <div class="cell margin-top-1 home-main__signs">
    <h2>Most viewed</h2>
    <div class="sign-grid">
      <%= render partial: "signs/card", collection: @viewed_signs, as: :sign %>
    </div>
  </div>
</div>