config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :signs
    resources :users
    resources :user_sign_transfers, only: %i[new create]
    resources :approved_user_applications, only: %i[index show] do
      member do
        post :accept
        post :decline
      end
    end
    resources :topics
    resources :comment_reports
    resources :exports, only: :index do
      get :published_signs, on: :collection
      get :users, on: :collection
      get :signbank, on: :collection
    end
    root to: "signs#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resource :styleguide, only: :show
  resources :users, only: :show, param: :username,
                    constraints: {
                      # Route constraints must be unanchored
                      username: Regexp.new(User::USERNAME_REGEXP.source.gsub(/\\A|\\Z/, ""))
                    }

  require "sidekiq/web"
  authenticate :user, ->(u) { u.administrator? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  root "home#index"
  resources :search, only: [:index]
  resources :public_signs, only: [:index]
  resources :approved_user_applications, only: %i[new create]
  resources :signs, except: %i[index] do
    resources :share, only: %i[show create destroy], controller: :sign_share, param: :token
    resources :comments, only: %i[create edit update destroy], controller: :sign_comments do
      resources :reports, only: :create, controller: :comment_reports
      resource :video, only: %i[update destroy], controller: :sign_video_comment
    end
    resources :video_comment, only: %i[create], controller: :sign_video_comment
    resources :sign_attachments, only: %i[create update destroy],
                                 path: "/:attachment_type",
                                 as: :attachments,
                                 constraints: { attachment_type: /usage_examples|illustrations/ }
    resource :agreement, only: %i[create destroy], controller: :sign_agreement
    resource :disagreement, only: %i[create destroy], controller: :sign_disagreement
    Sign.aasm.events.map(&:name).each do |event_name|
      patch event_name, on: :member, controller: :sign_workflow
    end

    collection do
      resources :batch_operation, only: :create,
                                  as: :signs_batch_operations,
                                  controller: :sign_batch_operations
    end
  end
  resources :sign_requests, only: :index

  resources :topics, only: %i[index show] do
    get :uncategorised, on: :collection
  end

  resources :folders do
    resources :share, only: %i[show create destroy], controller: :folder_share, param: :token
    resources :collaborations, controller: :collaborations
  end

  get "/videos/:id/:preset" => "videos#show", as: :video

  resources :folder_memberships, only: %i[create destroy]

  scope "/user" do
    resources :signs, only: [:index], as: :user_signs
  end
  post "/rails/active_storage/direct_uploads" => "direct_uploads#create"

  ##
  # Workaround a "bug" in lighthouse CLI
  #
  # Lighthouse CLI (versions 5.4 - 5.6 tested) issues a `GET /asset-manifest.json`
  # request during its run - the URL seems to be hard-coded. This file does not
  # exist so, during tests, your test will fail because rails will die with a 404.
  #
  # Lighthouse run from Chrome Dev-tools does not have the same behaviour.
  #
  # This hack works around this. This behaviour might be fixed by the time you
  # read this. You can check by commenting out this block and running the
  # accessibility and performance tests. You are encouraged to remove this hack
  # as soon as it is no longer needed.
  #
  if defined?(Shakapacker) && Rails.env.test?
    # manifest paths depend on your shakapacker config so we inspect it
    manifest_path = Shakapacker::Configuration
                    .new(root_path: Rails.root, config_path: Rails.root.join("config/shakapacker.yml"), env: Rails.env)
                    .public_manifest_path
                    .relative_path_from(Rails.public_path)
                    .to_s
    get "/asset-manifest.json", to: redirect(manifest_path)
  end

  get "/sitemap.xml" => "sitemaps#index", defaults: { format: "xml" }, as: :sitemap

  # This route acts as a catch-all, and so should always be placed at the end of the routes declaration
  # block
  get "/:page" => "static#show", as: :page
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < Administrate::ApplicationController
    include Administrate::Punditize
    include ActiveStorage::SetCurrent
    helper PresentersHelper

    before_action :authenticate_user!
    before_action { authorize :admin, :administrator_or_moderator? }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include ActiveStorage::SetCurrent
  include PresentersHelper

  before_action :store_user_location!, if: :storable_location?
  before_action :http_basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout -> { user_signed_in? ? "authenticated" : "application" }

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  protected

  ##
  # Rails' built in stale? caching helper method does not
  # respect whether caching is enabled or not.
  # While this is a different kind of cahing, it is unexpected
  # for an action to be served with 304 status in a development
  # or test environment.
  def stale?(*args)
    return true unless perform_caching

    super
  end

  def configure_permitted_parameters
    sign_in_attrs = %i[username email password password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: sign_in_attrs + %i[remember_me bio]
    devise_parameter_sanitizer.permit :account_update, keys: sign_in_attrs + %i[bio avatar]
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, alert: t("application.unauthorized") }
      format.js { render inline: "alert(\"#{t("application.unauthorized")}\");" } # rubocop:disable Rails/RenderInline
    end
  end

  def http_basic_auth
    return unless ENV["HTTP_BASIC_AUTH_USERNAME"] && ENV["HTTP_BASIC_AUTH_PASSWORD"]

    authenticate_or_request_with_http_basic("Username and Password please") do |username, password|
      username == ENV["HTTP_BASIC_AUTH_USERNAME"] && password == ENV["HTTP_BASIC_AUTH_PASSWORD"]
    end
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr? && !user_signed_in?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/sidebar/_signed_in.html.erb
<ul class="vertical menu icons">
   <li class="<%= current_page?("/") ? "menu-text--home is-active" : "menu-text--home" %>"><%= link_to root_path do %><%= inline_svg_pack_tag "static/images/home.svg", aria_hidden: true, class: "icon--medium" %><span>Home</span><% end %>
</ul>

<ul class="vertical menu icons">
  <li class="menu-text">Manage Signs</li>
  <li class="<%= current_page?("/signs/new") && "is-active" %>">
    <%= link_to new_sign_path do %>
      <%= inline_svg_pack_tag "static/images/add.svg", aria_hidden: true %><span>Add a sign</span>
    <% end %>
  </li>
  <li class="<%= current_page?("/user/signs") && "is-active" %>">
    <%= link_to user_signs_path do %>
      <%= inline_svg_pack_tag "static/images/ok.svg", aria_hidden: true %><span>My signs</span>
    <% end %>
  </li>
  <li class="<%= current_page?("/folders") && "is-active" %>"><a href="/folders"><%= inline_svg_pack_tag "static/images/folder-collection.svg", aria_hidden: true %><span>My folders</span></a></li>
</ul>

<% if current_user.moderator? || current_user.administrator? %>
  <ul class="vertical menu icons">
    <li class="menu-text">Admin Portal</li>
    <li class="<%= current_page?("/admin/signs") && "is-active" %>">
      <%= link_to admin_signs_path do %>
        <%= inline_svg_pack_tag "static/images/moderator.svg", aria_hidden: true %><span>Moderate signs</span>
      <% end %>
    </li>

    <% if current_user.administrator %>
      <li class="<%= current_page?("/admin/approved_user_applications") && "is-active" %>">
        <%= link_to admin_approved_user_applications_path do %>
          <%= inline_svg_pack_tag "static/images/tick.svg", class: 'icon--medium', aria_hidden: true %><span>User approvals</span>
        <% end %>
      </li>

      <li class="<%= current_page?("/admin/users") && "is-active" %>">
        <%= link_to admin_users_path do %>
          <%= inline_svg_pack_tag "static/images/users.svg", aria_hidden: true %><span>User admin</span>
        <% end %>
      </li>
      <li class="<%= current_page?("/admin/topics") && "is-active" %>">
        <%= link_to admin_topics_path do %>
          <%= inline_svg_pack_tag "static/images/tags.svg", class: 'icon--medium', aria_hidden: true %><span>Manage Topics</span>
        <% end %>
      </li>
      <li class="<%= current_page?("/admin/comment_reports") && "is-active" %>">
      <%= link_to admin_comment_reports_path do %>
        <%= inline_svg_pack_tag "static/images/comment.svg", aria_hidden: true %><span>Comment Reports</span>
      <% end %>
      </li>
      <li class="<%= current_page?("/admin/exports") && "is-active" %>">
      <%= link_to admin_exports_path do %>
        <%= inline_svg_pack_tag "static/images/table.svg", aria_hidden: true %><span>Export data</span>
      <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
<ul class="vertical menu icons hide-for-medium show-if-no-js">
  <li class="hide-if-no-js"> <!-- Don't need to duplicate the navbar here -->
    <a href="#">
      <img
        class="avatar"
        src="https://picsum.photos/id/550/20/20"
        alt="Profile Image"
      />
      <span><strong><%= current_user.username %></strong></span>
    </a>
  </li>
  <li><%= link_to "Edit my profile ›", edit_user_registration_path %></li>
  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
</ul>